### ISSUE TITLE
Add support for deleting users

### ISSUE THREAD

**Issue by spMohanty** [geotagx/pybossa#1]

**Comment by spMohanty** [comment]
@elliec , @supranove : Managed to add support for deleting users from the admin interface. You should see a `Manage Users` button on http://geotagx.org/admin/   

This takes you to a page which shows **all** registered users on geotagx, and not just the active ones as on the community page.   

When you delete any user, all the `task_runs` associated with that user is marked as anonymous, and instead of the `user_ip` that is usually associated with anonymous entries, I attach the old user_name of the deleted user to that field so that people studying the data can have a unique user identity associated with the data point.    

Also, if the user owns any projects, then the ownership of the projects will be transferred to the admin user who is deleting this user.

And, one cannot delete himself, or other admin users.

This has been implemented in the commits :  https://github.com/geotagx/geotagx-theme/commit/26cf2a57c966a7d639b4153b33b5d84d4b2b3f82 and https://github.com/geotagx/pybossa/commit/c66c9538eb174e7d429c7d1a6f1ee974c6e9316e

**Comment by othieno** [comment]
Really nice work @spMohanty  :+1: I gave it a test run and nothing out of the ordinary popped up.
