### ISSUE TITLE
Progress bar goes over 100% in new task

### ISSUE THREAD

**Issue by bcfuchs** [geotagx/pybossa#14]
Resets on completion of first subtask
Not sure if this is the right issues list for this...
![screen shot 2014-11-11 at 21 07 32](https://cloud.githubusercontent.com/assets/4658929/5000864/c8e635ca-69e7-11e4-8daa-bbb5700acbba.png)

Migrated from geotagx/geotagx-pybossa-archive#41

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in new geotagx project template
