### ISSUE TITLE
app loads full flickr images into thumbs  instead of flickr thumbs 

### ISSUE THREAD

**Issue by bcfuchs** [geotagx/pybossa#15]
e.g. this page

http://www.geotagx.org/app/category/identifyingdrought/

loads 

http://farm8.staticflickr.com/7140/13442558795_e94d4ce49b_z.jpg

instead of 

http://farm8.staticflickr.com/7140/13442558795_e94d4ce49b_m.jpg

or 

http://farm8.staticflickr.com/7140/13442558795_e94d4ce49b_s.jpg

Haven't looked at the code to see if there is an option to set this, but there should be one if there isn't, as it looks tacky at the moment.

Migrated from geotagx/geotagx-pybossa-archive#45

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in new geotagx
