### ISSUE TITLE
no link to resources in crop ID question

### ISSUE THREAD

**Issue by cobismith** [geotagx/pybossa#30]
from https://etherpad.mozilla.org/geotagx 
 --On Crop identification page, http://geotagx.org/app/cropid2/task/351
 I see this:
 Not in the list? Type your identification here, these resources could help your identification:

 But there is no link or clear next step to access more information....

Migrated from geotagx/geotagx-pybossa-archive#35

**Comment by elliec** [comment]
fixed in new template
