### ISSUE TITLE
registration questions 

### ISSUE THREAD

**Issue by cobismith** [geotagx/pybossa#31]
from https://etherpad.mozilla.org/geotagx

Registration process - the message say 'By click the Sign in button below you are agreeing to the terms of use and data.' and directs me towards pressing sign in button, but then I'm getting an error message 'Ooops, we didn't find you in the system, did you sign in?' so I'm lost! it should either put me automatically on create new account or change the instruction on the error message 'please use 'create new account' 
Message ' I'm happy to be part of the Cyberlab research project! what is it and why should I join, what are the implications of signing? 

Migrated from geotagx/geotagx-pybossa-archive#36

**Comment by elliec** [comment]
fixed in new geotagx
