### ISSUE TITLE
task IDs don't work with new parent/child code

### ISSUE THREAD

**Issue by cobismith** [geotagx/pybossa#36]
the new code for child modules linked to 1 parent module dataset means that the display interface and links don't work in child modules. For example, http://geotagx.org/app/geotagebola/task/2095 gives message: 

> Error! This task does not belong to geotagebola

because that task ID is from the parent ebola module. User interface & documentation work needed to support new code. 

Migrated from geotagx/geotagx-pybossa-archive#42

**Comment by elliec** [comment]
fixed in new Geotagx
