### ISSUE TITLE
Support a federated login system (please!!)

### ISSUE THREAD

**Issue by blahah** [geotagx/pybossa#5]
Users are driven away by signup forms. Federated logins are much much easier, save everyone time, and are generally more likely to be secure.

Please support them (Google, Facebook, Twitter, Persona, Github) and drop the user signup form.

Migrated from geotagx/geotagx-pybossa-archive#28

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in new geotagx
