### ISSUE TITLE
Entry for "other" animal remains from one photo to the next 

### ISSUE THREAD

**Issue by fischhoff** [geotagx/pybossa#51]
In the: "Condition of animals and livestock" application: I entered "cheetah" for the cheetah picture. When I moved on to the next picture (of a Grevy's zebra), it still said cheetah. I think it would be better for it to be blank

Migrated from geotagx/geotagx-pybossa-archive#25

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in the new version of Geotag-X
