### ISSUE TITLE
Can't geo localise image, doesn't switch to new one after saying I don't know

### ISSUE THREAD

**Issue by kathayes12** [geotagx/pybossa#57]
When I can't geo localise an image I click the I don't know button but nothing happens. It's been explained to me that I need to click Ok, save my answer, to move to the next picture but this isn't made explicit in the notes and is counter intuitive. It would be helpful if a new image loaded after clicking I don't know, or if it was made clear to click another button. 

Migrated from geotagx/geotagx-pybossa-archive#18

**Comment by elliec** [comment]
thanks for the feedback, this has been fixed in the new version of Geotag-X
