### ISSUE TITLE
Sometimes main content becomes blank

### ISSUE THREAD

**Issue by wavesoft** [geotagx/pybossa#7]
In two cases (so far) I was redirected into a blank content page. The header and the footer were still visible, but the main content was just blank.
- The first time I created an account and when I submitted the form I saw this blank page. I then clicked on "Projects", it worked as expected and in addition I saw a 'You have been successfully registered' message.
- The second time it happened when I completed a task and I clicked 'Projects' in order to navigate away. I saw again a blank screen. When I clicked 'Projects' the second time it worked as expected.

Migrated from geotagx/geotagx-pybossa-archive#23

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in new geotagx
