### ISSUE TITLE
Project stats page gives unhelpful error

### ISSUE THREAD

**Issue by IknowJoseph** [geotagx/pybossa#9]
I have created an account after being prompted by clicking the stats link for a project. Once logged in I am told "You do not have the permission to access the requested resource. It is either read-protected (i.e. the application is hidden) or not readable by the server."

Could this be more explicit about the error? Presumably I don't have access because I'm not a project admin, but it would be nice to be told.

Migrated from geotagx/geotagx-pybossa-archive#12

**Comment by elliec** [comment]
Hi, thanks for the feedback, this should be fixed in new geotagx
